name: mistake_correction
dataset_path: eth-nlped/stepverify
dataset_name: default
training_split: train
test_split: train
system_prompt: |
  You are a helpful math tutor assisting a student. Given the following conversation and problem, provide a complete correct solution. Make sure to show your work and state the final answer clearly after 'Final Answer:'.
  Problem: {{question}}
  Conversation:
  {{dialog_history}}
  Student: {{student_chat_solution}}
  Teacher: 
ground_truth_format: "{{ reference_solution.split('\n')[-1].replace(',', '').strip() }}"
few_shot_samples: ""
stop: ["Problem:", "Student:"]
